from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from my_app.database import get_db
from my_app.auth.auth_handler import (
    create_access_token,
    create_refresh_token,
    verify_refresh_token,
    revoke_refresh_token,
    revoke_all_sessions,
)
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.models.device_session import DeviceSession
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEYfrom fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from my_app.database import get_db
from my_app.auth.auth_handler import (
    create_access_token,
    create_refresh_token,
    verify_refresh_token,
    revoke_refresh_token,
    revoke_all_sessions,
)
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.models.device_session import DeviceSession
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY
from my_app.auth.auth_handler import ACCESS_TOKEN_EXPIRE_MINUTES
from my_app.auth.auth_handler import ALGORITHM
from my_app.auth.auth_handler import SECRET_KEY